# Generated by Django 4.0 on 2024-09-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='state',
        ),
        migrations.AddField(
            model_name='userregister',
            name='Address',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
