# Generated by Django 4.0 on 2024-09-14 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_btest6_btest5_btest4_btest3_btest2_btest1'),
    ]

    operations = [
        migrations.CreateModel(
            name='blood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('testname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='urine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('testname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='btest2',
            name='report',
        ),
        migrations.RemoveField(
            model_name='btest3',
            name='report',
        ),
        migrations.RemoveField(
            model_name='btest4',
            name='report',
        ),
        migrations.RemoveField(
            model_name='btest5',
            name='report',
        ),
        migrations.RemoveField(
            model_name='btest6',
            name='report',
        ),
        migrations.RenameField(
            model_name='ourservices',
            old_name='blood',
            new_name='test',
        ),
        migrations.RemoveField(
            model_name='ourservices',
            name='calcium',
        ),
        migrations.RemoveField(
            model_name='ourservices',
            name='crp',
        ),
        migrations.RemoveField(
            model_name='ourservices',
            name='ctscan',
        ),
        migrations.RemoveField(
            model_name='ourservices',
            name='thayroid',
        ),
        migrations.RemoveField(
            model_name='ourservices',
            name='ultrasound',
        ),
        migrations.RemoveField(
            model_name='ourservices',
            name='urine',
        ),
        migrations.RemoveField(
            model_name='ourservices',
            name='xray',
        ),
        migrations.DeleteModel(
            name='btest1',
        ),
        migrations.DeleteModel(
            name='btest2',
        ),
        migrations.DeleteModel(
            name='btest3',
        ),
        migrations.DeleteModel(
            name='btest4',
        ),
        migrations.DeleteModel(
            name='btest5',
        ),
        migrations.DeleteModel(
            name='btest6',
        ),
        migrations.AddField(
            model_name='urine',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ourservices'),
        ),
        migrations.AddField(
            model_name='blood',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ourservices'),
        ),
    ]
