# Generated by Django 4.0 on 2024-09-16 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_xray_ultrasound_thayroid_ctscan_crp_calcium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blood',
            name='test',
        ),
        migrations.RemoveField(
            model_name='calcium',
            name='test',
        ),
        migrations.RemoveField(
            model_name='crp',
            name='test',
        ),
        migrations.RemoveField(
            model_name='ctscan',
            name='test',
        ),
        migrations.RemoveField(
            model_name='thayroid',
            name='test',
        ),
        migrations.RemoveField(
            model_name='ultrasound',
            name='test',
        ),
        migrations.RemoveField(
            model_name='urine',
            name='test',
        ),
        migrations.RemoveField(
            model_name='xray',
            name='test',
        ),
        migrations.DeleteModel(
            name='ourservices',
        ),
    ]
